### ISSUE TITLE
Init

### ISSUE THREAD

**Issue by 4kimov** [sqids/sqids-java#1]
Hey @fanweixiao / @0x3333, Sqids is live, would you like to give [this implementation a shot](https://github.com/sqids/sqids-spec#-porting-to-a-new-language)?

**Comment by fanweixiao** [comment]
Hi @4kimov, working on the first impl, hope will push in next week.

**Comment by 4kimov** [comment]
Right on 💪  Let me know if you have questions/etc

**Comment by 0x3333** [comment]
> Hi @4kimov, working on the first impl, hope will push in next week.

Which minimum java version will be supported?

**Comment by 4kimov** [comment]
@fanweixiao How's it going with this repo?

**Comment by lukechen116** [comment]
Hello @4kimov, I implemented Java code for Sqids. I would like to contribute this code and upload branch. How do I provide?

**Comment by 4kimov** [comment]
Hi @lukechen116, nice - thank you & good job 👍 Sent you an invite to be a maintainer. Feel free to remove the CHANGELOG, release package, etc

I'll update the site shortly.

**Comment by lukechen116** [comment]
@4kimov I changed constructor to Gang of Four (GoF) design Builder pattern that is friendly readable code and constructor default parameters are reduced. Would you update official site example code?

**Comment by lukechen116** [comment]
@4kimov Thank you.
1. Setup completed. This is my first time using GitHub Actions, so it took a little longer. Sorry for the delay.
2. CHANGELOG doesn't affect the Java project or packages. I'm keeping it for future use.

**Comment by 4kimov** [comment]
@lukechen116 Perfect, thank you 👍

**Comment by lukechen116** [comment]
Hello @4kimov / @fanweixiao / @0x3333
I have tested it almost.
Could you assist me to package and publish it to the Maven repository for public use?

**Comment by fanweixiao** [comment]
Hi @lukechen116, the maven repository is maintained by @0x3333, he will help in this. But he's got busy these days.

**Comment by 0x3333** [comment]
I'll issue a PR with the settings to Gradle to allow publishing to the Maven repo. I'll ask for some time, as things are really stacking up here.

**Comment by lukechen116** [comment]
@0x3333 / @fanweixiao, thank you for all the help! Please let me know if anything else is needed or suggested.
@4kimov  Could you invite @0x3333 to be the maintainer for this repo?
